language: objective-c
osx_image: xcode7.2

before_install:
  - brew update
  - brew install carthage || brew outdated carthage || brew upgrade carthage
  - carthage version

install:
  - gem install xcpretty
  - carthage bootstrap --no-use-binaries --platform ios

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="Routing"
    - IOS_SDK=iphonesimulator9.2
  matrix:
    - DESTINATION="OS=9.2,name=iPhone 6S Plus"     SCHEME="iOS"     SDK="$IOS_SDK"     ACTION="test"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    -project "$FRAMEWORK_NAME.xcodeproj"
    -scheme "$FRAMEWORK_NAME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    "$ACTION"
    | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)

