language: objective-c
osx_image: xcode7.3

before_install:
  - brew update
  - brew install carthage || brew outdated carthage || brew upgrade carthage
  - carthage version

install:
  - gem install xcpretty
  - carthage bootstrap --no-use-binaries --platform ios,mac

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="Routing"
    - IOS_SDK=iphonesimulator9.3
    - OSX_SDK=macosx10.11
    - TVOS_SDK=appletvsimulator9.1 
    - WATCHOS_SDK=watchsimulator2.1
  matrix:
    - DESTINATION="OS=9.3,name=iPhone 6S Plus"     SCHEME="iOS"     SDK="$IOS_SDK"     ACTION="test"
    - DESTINATION="arch=x86_64"                    SCHEME="OSX"     SDK="$OSX_SDK"     ACTION="test"
    - DESTINATION="OS=9.1,name=Apple TV 1080p"     SCHEME="tvOS"    SDK="$TVOS_SDK"    ACTION="build"
    - DESTINATION="OS=2.1,name=Apple Watch - 38mm" SCHEME="watchOS" SDK="$WATCHOS_SDK" ACTION="build"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    -project "$FRAMEWORK_NAME.xcodeproj"
    -scheme "$FRAMEWORK_NAME $SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=NO
    "$ACTION"
    | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)

